# Server
server.port=8081

# Kafka - Aiven
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}
spring.kafka.properties.security.protocol=SASL_SSL
spring.kafka.properties.sasl.mechanism=SCRAM-SHA-256
spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}";
spring.kafka.properties.ssl.truststore.type=JKS
spring.kafka.properties.ssl.truststore.location=/home/ec2-user/kafka-truststore.jks
spring.kafka.properties.ssl.truststore.password=changeit

# Topic
kafka.topic.customer-events=customer-events

# Actuator
management.endpoints.web.exposure.include=health,info

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html