spring.application.name=payload-producer

server.port = 8081

# Kafka broker address - where our Kafka container is running
spring.kafka.bootstrap-servers = localhost:9092

# Topic name - where this service publishes events
kafka.topic.customer-events=customer-events

management.endpoints.web.exposure.include=health,info

springdoc.swagger-ui.path=/swagger-ui.html