# Server
server.port=8083

# Kafka - Aiven
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}
spring.kafka.properties.security.protocol=SASL_SSL
spring.kafka.properties.sasl.mechanism=SCRAM-SHA-256
spring.kafka.properties.sasl.jaas.config=${KAFKA_JAAS_CONFIG}
spring.kafka.properties.ssl.truststore.type=JKS
spring.kafka.properties.ssl.truststore.location=/home/ec2-user/kafka-truststore.jks
spring.kafka.properties.ssl.truststore.password=changeit
spring.kafka.consumer.group-id=delivery-service-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer

# Kafka topics
kafka.topic.email-events=email-events
kafka.topic.sms-events=sms-events
kafka.topic.push-events=push-events

# Mail - AWS SES
spring.mail.host=email-smtp.us-east-2.amazonaws.com
spring.mail.port=587
spring.mail.username=${SES_USERNAME}
spring.mail.password=${SES_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Email sender
mail.from=${SES_FROM_EMAIL}

# Actuator
management.endpoints.web.exposure.include=health,info